#.infrastructure/todoapp-pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todoapp-container
    image: leoleiden/todoapp:3.0.0
    ports:
    - containerPort: 8000
    env:
    - name: DJANGO_SETTINGS_MODULE
      value: todolist.settings
    - name: SECRET_KEY
      value: "your-super-secret-key-for-production" # У продакшн використовуйте Kubernetes Secrets
    - name: DEBUG
      value: "False"
    - name: ALLOWED_HOSTS
      value: "localhost,127.0.0.1"

    livenessProbe:
      httpGet:
        path: /api/health/liveness/
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    readinessProbe:
      httpGet:
        path: /api/health/readiness/
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3